### ISSUE TITLE
Can't serve nor build...

### ISSUE THREAD

**Issue by Guzmank90** [zoton2/nodecg-vue-ts-template#12]
Hello,
I'm using the original package and not satisfied with ui, want it fully changed, I'm familar with Quasar and Vue so your project fits perfectly for me, Just... how to run it?
Cloned the repo -> did npm install.. did try npm run start but it fails, building fails as well.
how do you run it??

**Comment by zoton2** [comment]
You'll have to be more specific about your issues. What is the "original package" you mention? And something that might not be completely clear in the README, this is a template for a bundle used by the [NodeCG](https://github.com/nodecg/nodecg) framework, so this bundle has to be installed inside an instance of that too. Builds will probably fail without that, and `npm start` triggers NodeCG to start so will not work either.

**Comment by Guzmank90** [comment]
I though it's an alternative, guess it's not.
Using as the template isn't clear, would be nice to know template of what :(.

currently, using original nodecg let's you build within panels. i want to customize those panels so they break properly on smaller devices and the panel column is to small(col-8; want to bump it to full-width). I Want to change the main UI as well, customize and add to it.
As I'm more comfortable with vue so i was thinking this version would be a better fit.

**Comment by zoton2** [comment]
Unfortunately this is just a template for a bundle *within* NodeCG so this cannot help there, sorry. The development on NodeCG itself has been a bit lacking recently, but we do have a NodeCG discord where you could discuss your issues with other people too and see if they have any good solutions.

**Comment by Guzmank90** [comment]
Thanks
